---

- name: install tomcat8
  apt:
    name: '{{ tomcat8_packages }}'
    state: present
    cache_valid_time: 3600

- name: install tomcat8 admin
  apt:
    name: '{{ tomcat8_admin_packages }}'
    state: present
    cache_valid_time: 3600
  when: tomcat8_admin_install

- name: start tomcat8
  service:
    name: tomcat8
    state: started
